### PR TITLE
created alt nucleus, cytoplasm, and cell mask

### PR DESCRIPTION
**Pull request by shanrhoads**
Completed:
- Created new notebooks describing 1) how to segment the cytoplasm (cytoplasm_from_composite) from an aggregate of multiple channels (assuming the channels fill the entire cytoplasm area, but don't fill the nucleus), and 2) how to segment the nucleus and cell masks from the cytoplasm mask.
- Created a worflow based on the cytoplasm_from_composite notebook process. It seems to have worked, but there is a seemingly unrelated bug in the plugin that won't allow any workflows to run past set 2 (step 3 --> error message).
Screenshot 2023-03-28 161439

Still need to:
- create workflow for nucleus and cell mask from cytoplasm mask

### CODE REVIEW

**Comment by cjsifuen** [comment]
@shanrhoads , in regards to the error, is there naming convention for files or objects different than it was? It looks like the code was trying to split on ":", but there was none.

**Comment by shanrhoads** [comment]
@cjsifuen Yes - it seems to have something to do with how the plugin is handling the file names. The original file does not have ":" in the name, but all of the outputs from the plugin workflows have something like "0:" to start. The weird part about the issue is that I can get through the first two steps in each workflow without issue, but step number 3 results in error despite the same file handling being used in each step (at least I think). Hoping @ergonyc has dealt with this before and has a possible solution.

**Comment by ergonyc** [comment]
The bugs should have been handled with a hack to append a '-' to all filenames when naming the layer.  There is some HACK logic for choosing the right layer in the workflows that makes assumpitions about ordering based on the opening "numeric" of the layer name.

This is all part of a bigger issue of how napari handles layer names:  namely as python sets.  So keeping track of the ordering of them is impossible.

The resulting HACK logic for the workflow steps is to always choose the "maximum" or highest numbered which corresponds to the most recent output for each step.  That means if you don't want to use the most-recent it must be deleted.

**Comment by ergonyc** [comment]
Closing this PR with the file change orphans.  @shanrhoads I think we have discussed all the particular changes, and you can merge in nesecssary ones later... 

Note: we have already done a "breaking" merge which renames the module to "infer_subc" and depricated the 2D

**Pull request closed without merging**
